[package]
name = "day05"
version = "0.1.0"
authors = ["Kunal Arya <me@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.*"
common = { path = "../common" }
